[package]
name = "orbrs"
version = "0.1.0"
authors = ["patrickisroman <>"]
edition = "2018"

[profile.release]
opt-level = 3

[dependencies]
bitvector = "0.1.5"
cgmath = "0.18.0"
image = "0.25.1"
imageproc = "0.25.0"
rand = "0.8.5"
